// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myDemoApp.API.Data;

namespace myDemoApp.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190507230610_AddedEmployeeDataEntity")]
    partial class AddedEmployeeDataEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("myDemoApp.API.Models.EmployeeData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DOB");

                    b.Property<string>("Designation");

                    b.Property<string>("Name");

                    b.Property<string>("email");

                    b.HasKey("Id");

                    b.ToTable("EmployeeDatas");
                });

            modelBuilder.Entity("myDemoApp.API.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
